services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StronkPassw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - data:/var/opt/mssql

volumes:
  data:
